version: "3.1"
services:
    db:
        image: mysql:8.0
        restart: always
        ports: 
            - "3306:3306"
        command: --local-infile=1 --secure-file-priv=/docker-entrypoint-initdb.d
        environment:
            # DO NOT FORGET TO UPDATE YOUR DATABASE, USERNAME, AND PASSWORD WITH THAT OF YOUR GROUP!
            MYSQL_DATABASE: group05
            MYSQL_USER: group05
            MYSQL_PASSWORD: group05
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
        networks:
            - default
    
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db:ms8db
        networks:
            - default
        depends_on:
            - db
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:ms8db
        ports:
            - 8080:80
        depends_on:
            - db
            - www
